# Generated by Django 3.2.6 on 2023-10-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
